### PR TITLE
stuff

### PR DESCRIPTION
**Pull request by Gamerein**
Not expecting you to accept it but just take a look at it

### CODE REVIEW

**Comment by ParadoxOrigins** [comment]
i'll get back on that soon too

**Comment by Gamerein** [comment]
Oh I actually thought you already rejected this... I have implemented all of these commands into my own bot already

**Comment by ParadoxOrigins** [comment]
nein i just forgot about it, i actually plan to merge at least the udefine and weather command

**Comment by Gamerein** [comment]
You already have udefine though, I only used a different API

**Comment by ParadoxOrigins** [comment]
yeah it only use the official api instead of some lame wrapper, but didn't switched myself so i'll just merge lul

**Comment by Gamerein** [comment]
This is has been in review for 2 months now https://cdn.discordapp.com/emojis/377110562116468766.png

**Comment by InternalCosmos** [comment]
wew

**Comment by ParadoxOrigins** [comment]
So, this PR is planned to stay open until the v4 release, which is planned to include the following changes of this PR:
-Use the urban dictionary API directly instead of a middle man
-Weather command

**Comment by ParadoxOrigins** [comment]
Partially merged with #156

**Pull request closed without merging**
